"""add_telegram_handle_to_bot_config

Revision ID: 1a8292c6f573
Revises: ee3dd455a639
Create Date: 2026-05-03 03:33:52.851542

Adds the nullable `telegram_handle` column to `bot_config`. This is the
per-tenant Telegram chat target for escalation notifications. Sent in
addition to (not instead of) the platform-wide TELEGRAM_CHAT_ID.

Hand-written rather than autogenerated — autogenerate keeps producing
schema-drift noise on this DB and we don't want that landing in a
single-purpose additive migration.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a8292c6f573'
down_revision: Union[str, Sequence[str], None] = 'ee3dd455a639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add telegram_handle to bot_config."""
    op.add_column(
        'bot_config',
        sa.Column('telegram_handle', sa.String(), nullable=True),
    )


def downgrade() -> None:
    """Drop telegram_handle from bot_config."""
    op.drop_column('bot_config', 'telegram_handle')
