"""Enable RLS on all public tables to suppress Supabase PostgREST exposure warnings.

Hand-written rather than autogenerated — RLS is a Postgres security directive,
not a schema change; Alembic autogenerate does not detect or emit it.

Context: SupportBot Studio uses a direct Postgres connection via transaction
pooler (SQLAlchemy). PostgREST / Supabase REST API is NOT used. Enabling RLS
with zero policies blocks all PostgREST access while leaving the direct
connection completely unaffected (RLS is bypassed for superuser / service-role
connections that Alembic and FastAPI use).

Revision ID: 3dde98ecabc1
Revises: 3f4c1e9b8a25
Create Date: 2026-05-11 23:56:55.612681

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '3dde98ecabc1'
down_revision: Union[str, Sequence[str], None] = '3f4c1e9b8a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_TABLES = [
    "alembic_version",
    "bot_config",
    "brand_voices",
    "conversations",
    "error_logs",
    "faq_entries",
    "leads",
    "messages",
    "pending_escalations",
    "report_schedules",
    "revoked_tokens",
    "sales_configs",
    "super_admins",
    "tenants",
    "usage_logs",
    "visitor_conversations",
    "visitors",
    "webhook_configs",
]


def _is_postgres() -> bool:
    """Skip on SQLite local-dev — RLS is Postgres-only DDL."""
    bind = op.get_bind()
    return bind.dialect.name == "postgresql"


def upgrade() -> None:
    if not _is_postgres():
        return
    for table in _TABLES:
        op.execute(f"ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY;")


def downgrade() -> None:
    if not _is_postgres():
        return
    for table in _TABLES:
        op.execute(f"ALTER TABLE public.{table} DISABLE ROW LEVEL SECURITY;")
