"""add_revoked_tokens_table

Revision ID: 3f4c1e9b8a25
Revises: 1a8292c6f573
Create Date: 2026-05-06 00:00:00.000000

Adds the `revoked_tokens` table — JWT denylist for early revocation on
logout. Tokens still expire naturally via the `exp` claim; this table
just kills them sooner. The `jti` column matches the `jti` claim set
on every token at issue time (uuid4 hex). UNIQUE on jti because
re-revoking the same token must be a no-op.

Hand-written rather than autogenerated — autogenerate keeps producing
schema-drift noise on this DB and we don't want that landing in a
single-purpose additive migration.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f4c1e9b8a25'
down_revision: Union[str, Sequence[str], None] = '1a8292c6f573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create revoked_tokens table."""
    op.create_table(
        'revoked_tokens',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('jti', sa.String(), nullable=False),
        sa.Column('revoked_at', sa.DateTime(), nullable=False),
        sa.UniqueConstraint('jti', name='uq_revoked_tokens_jti'),
    )
    op.create_index('ix_revoked_tokens_jti', 'revoked_tokens', ['jti'])


def downgrade() -> None:
    """Drop revoked_tokens table."""
    op.drop_index('ix_revoked_tokens_jti', table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
