"""Add phone column to leads and make email nullable.

The inline lead-capture form (ChatWidget.jsx) collects three optional fields
— name, email, phone — and lets the visitor Skip them all. We still want a
Lead row to fire the lead_captured webhook even when every field is empty,
so email needs to be nullable; phone is a brand-new column.

Hand-written (not autogenerated): SQLite has no native ALTER COLUMN, so the
column-nullability change uses Alembic's batch_alter_table mode which
rebuilds the table on SQLite and emits a plain ALTER on Postgres. The phone
column add is straightforward and works on both.

Revision ID: 8b570dde7af4
Revises: 3dde98ecabc1
Create Date: 2026-05-12 00:46:15.457887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b570dde7af4'
down_revision: Union[str, Sequence[str], None] = '3dde98ecabc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table("leads") as batch_op:
        batch_op.add_column(sa.Column("phone", sa.String(), nullable=True))
        batch_op.alter_column(
            "email",
            existing_type=sa.String(),
            nullable=True,
        )


def downgrade() -> None:
    with op.batch_alter_table("leads") as batch_op:
        # Reversing the nullable change is best-effort: if rows with NULL email
        # exist at downgrade time, Postgres will reject the NOT NULL switch.
        # That's intentional — refusing to silently drop data.
        batch_op.alter_column(
            "email",
            existing_type=sa.String(),
            nullable=False,
        )
        batch_op.drop_column("phone")
