"""add_custom_instructions_to_bot_config_and_escalation_reason_to_leads

Revision ID: b2c4e6f8a1d3
Revises: f7e8d9c0b1a2
Create Date: 2026-05-15 09:00:00.000000

Adds two nullable columns to support the chain-of-thought prompt upgrade:

  1. bot_config.custom_instructions (Text, nullable)
     Per-tenant free-text instructions appended to the system prompt AFTER
     all platform rules. Empty/null means "no overrides" — the bot uses the
     default behavior. Appended last by design: tenant-controlled text
     cannot override the system rules above it (prompt-injection defence).

  2. leads.escalation_reason (String, nullable, indexed)
     Why the bot escalated this conversation — one of:
       explicit_request | frustration | urgency | sensitive_topic |
       unresolved_loop | no_faq_answer
     Written when ``type='escalation'`` rows are created from the
     escalate flow. Indexed because the Leads dashboard filters by reason.
     Lead.type already distinguishes lead-vs-escalation; reason adds the
     orthogonal "what kind of escalation" facet without overloading type.

Hand-written rather than autogenerated — autogenerate produces RLS / schema
drift noise on this DB. Both columns are nullable so the migration is safe
to apply without a backfill: existing rows simply have NULL values.
Column additions are idempotent — inspector checks skip existing columns.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection


# revision identifiers, used by Alembic.
revision: str = 'b2c4e6f8a1d3'
down_revision: Union[str, Sequence[str], None] = 'f7e8d9c0b1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add custom_instructions to bot_config and escalation_reason to leads.

    Both column additions are guarded by inspector checks so they can
    safely run against a database where the columns already exist
    (e.g. Supabase production where columns were manually backfilled).
    """
    bind = op.get_bind()
    inspector = reflection.Inspector.from_engine(bind)

    bot_config_cols = {c['name'] for c in inspector.get_columns('bot_config')}
    leads_cols = {c['name'] for c in inspector.get_columns('leads')}

    if 'custom_instructions' not in bot_config_cols:
        op.add_column(
            'bot_config',
            sa.Column('custom_instructions', sa.Text(), nullable=True),
        )
    if 'escalation_reason' not in leads_cols:
        op.add_column(
            'leads',
            sa.Column('escalation_reason', sa.String(), nullable=True),
        )
    op.create_index(
        'ix_leads_escalation_reason',
        'leads',
        ['escalation_reason'],
        if_not_exists=True,
    )


def downgrade() -> None:
    """Drop the columns and index added in upgrade()."""
    op.drop_index('ix_leads_escalation_reason', table_name='leads')
    op.drop_column('leads', 'escalation_reason')
    op.drop_column('bot_config', 'custom_instructions')
