"""Add type and status columns to leads.

The unified Leads tab surfaces both buying-intent captures AND escalations in
one table. Distinguishing them at write-time keeps the query simple — a single
indexed Lead.type filter beats UNION-ing against the conversations table.

- type:   "lead" | "escalation"  (default "lead" — preserves legacy rows)
- status: "new" | "contacted" | "qualified" | "lost"  (default "new")

Hand-written (not autogenerated): autogenerate would emit add_column but not
populate the new columns on existing rows; we want explicit server-side
defaults so legacy data lights up as type=lead, status=new immediately.

Revision ID: d5465a04bb14
Revises: 8b570dde7af4
Create Date: 2026-05-12 00:49:30.075544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5465a04bb14'
down_revision: Union[str, Sequence[str], None] = '8b570dde7af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default ensures existing rows get the value backfilled by the
    # database itself, not by Python — fast on tables of any size.
    with op.batch_alter_table("leads") as batch_op:
        batch_op.add_column(
            sa.Column("type", sa.String(), nullable=False, server_default="lead")
        )
        batch_op.add_column(
            sa.Column("status", sa.String(), nullable=False, server_default="new")
        )
        batch_op.create_index("ix_leads_type", ["type"])
        batch_op.create_index("ix_leads_status", ["status"])


def downgrade() -> None:
    with op.batch_alter_table("leads") as batch_op:
        batch_op.drop_index("ix_leads_status")
        batch_op.drop_index("ix_leads_type")
        batch_op.drop_column("status")
        batch_op.drop_column("type")
