"""Add type and status columns to leads.

The unified Leads tab surfaces both buying-intent captures AND escalations in
one table. Distinguishing them at write-time keeps the query simple — a single
indexed Lead.type filter beats UNION-ing against the conversations table.

- type:   "lead" | "escalation"  (default "lead" — preserves legacy rows)
- status: "new" | "contacted" | "qualified" | "lost"  (default "new")

Hand-written (not autogenerated): autogenerate would emit add_column but not
populate the new columns on existing rows; we want explicit server-side
defaults so legacy data lights up as type=lead, status=new immediately.
Column additions are idempotent — inspector checks skip existing columns.

Revision ID: d5465a04bb14
Revises: 8b570dde7af4
Create Date: 2026-05-12 00:49:30.075544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection


# revision identifiers, used by Alembic.
revision: str = 'd5465a04bb14'
down_revision: Union[str, Sequence[str], None] = '8b570dde7af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = reflection.Inspector.from_engine(bind)
    leads_cols = {c['name'] for c in inspector.get_columns('leads')}

    with op.batch_alter_table("leads") as batch_op:
        if 'type' not in leads_cols:
            batch_op.add_column(
                sa.Column("type", sa.String(), nullable=False, server_default="lead")
            )
        if 'status' not in leads_cols:
            batch_op.add_column(
                sa.Column("status", sa.String(), nullable=False, server_default="new")
            )
    # Indexes outside batch context — if_not_exists is supported on
    # op.create_index but not on batch_op.create_index.
    op.create_index("ix_leads_type", "leads", ["type"], if_not_exists=True)
    op.create_index("ix_leads_status", "leads", ["status"], if_not_exists=True)


def downgrade() -> None:
    with op.batch_alter_table("leads") as batch_op:
        batch_op.drop_index("ix_leads_status")
        batch_op.drop_index("ix_leads_type")
        batch_op.drop_column("status")
        batch_op.drop_column("type")
