"""add_brand_voices_table

Revision ID: ee3dd455a639
Revises: 2d167a3fc61d
Create Date: 2026-05-03 03:19:49.157089

Adds the `brand_voices` table for the Brand Voice DNA feature.
One row per tenant, enforced by the unique constraint on bot_id.

Hand-written (not autogenerated) to avoid the schema drift noise the
autogenerate run keeps producing on this DB (orphan backup tables,
String/Text type churn, FK shuffle on visitor_conversations).
Additive only — no drops, no renames, no data movement.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee3dd455a639'
down_revision: Union[str, Sequence[str], None] = '2d167a3fc61d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create brand_voices table."""
    op.create_table(
        'brand_voices',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('bot_id', sa.String(), nullable=False),
        sa.Column('tone', sa.String(), nullable=True),
        sa.Column('vocabulary', sa.Text(), nullable=True),
        sa.Column('personality_traits', sa.Text(), nullable=True),
        sa.Column('avoid', sa.Text(), nullable=True),
        sa.Column('raw_samples', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('generated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.UniqueConstraint('bot_id', name='uq_brand_voice_bot'),
    )
    op.create_index('ix_brand_voices_id', 'brand_voices', ['id'], unique=False)
    op.create_index('ix_brand_voices_bot_id', 'brand_voices', ['bot_id'], unique=False)


def downgrade() -> None:
    """Drop brand_voices table."""
    op.drop_index('ix_brand_voices_bot_id', table_name='brand_voices')
    op.drop_index('ix_brand_voices_id', table_name='brand_voices')
    op.drop_table('brand_voices')
